version: 0.2
phases:
  pre_build:
    commands:
      - "echo logging in to ECR registry"
      - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building docker image"
      - "docker build -t code-pipeline-project ."
      - "docker tag code-pipeline-project:latest 846562901861.dkr.ecr.us-east-1.amazonaws.com/code-pipeline-project:latest"
  post_build:
    commands:
      - "echo Build is complete on `date`"
      - "echo Pushing the docker image"
      - "docker push 846562901861.dkr.ecr.us-east-1.amazonaws.com/code-pipeline-project:latest"